### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by foxpcteam** [siteorigin/so-css#1]
Hi,
1. dose the plugin full support RTL?

2. can we work(eidt) on any page in out website or its support only homepage?

**Comment by Misplon** [comment]
Hi @foxpcteam

There are no specific RTL considerations at the moment. The same Custom CSS will be printed regardless of the whether the site is using a LTR or RTL language. If the site is using a RTL language, custom CSS will still be applied. Do you see a problem with this?

When in the Custom CSS visual mode there is an inspector at the bottom of the window. To browse your site, de-select the magnifying glass icon. This will disable the inspector and allow normal site navigation.
