### ISSUE TITLE
Add sticky to the Property setting

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-css#113]
`sticky` is missing from the Position property value options. 

https://www.w3schools.com/cssref/pr_class_position.asp

Ensure that all available values are added to the position property.

**Comment by AlexGStapleton** [comment]
`sticky` requires `top` to be set for it to work. How do you want to handle `top`? I've had a quick look and the interface is really set up for value detection as _none_ of the fields have unique ids or classes. Hm. I could use nth but that's not really ideal.

**Comment by AlexGStapleton** [comment]
I've talked with @Misplon about this and we've decided its best we leave this for the moment. The SiteOrigin CSS Editor interface was built in a way that doesn't really allow conditional settings without some major adjustments to how fields are handled. Specifically, none of the fields are unique - they're all generic inputs with no class or id. This makes it really tricky to create events specific to certain settings without also adding significant general checks to all fields. These sort of changes aren't 

You can manually do by following [these instructions](https://www.w3schools.com/howto/howto_css_sticky_element.asp).
