### ISSUE TITLE
Click link that links to current page and inspector will display, "Navigation To: :"

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#14]
[Reported in this thread](https://siteorigin.com/thread/using-custom-css-on-pages-besides-home-page)

When you click a link that is for the same page, "Navigation To: :" appears in place of a normal link. It might be a better idea to display nothing rather than showing a link to the current page.

![image of inspector displaying Navigation To: :](https://i.imgur.com/aXMWB3g.png)

**Comment by gregpriday** [comment]
Definitely worth fixing up.

**Comment by AlexGStapleton** [comment]
I can confirm this no longer happens.
