### ISSUE TITLE
The AGP Font Awesome Collection plugin causes Inspector to be unable to detect mouse clicks.

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#15]
The [AGP Font Awesome Collection](https://wordpress.org/plugins/agp-font-awesome-collection/) is a decently popular plugin with 10,000+ active installs. It includes page builder widgets so it might be a good idea to fix it as they are likely to be used together. Here's a screenshot of my console when the plugin is active, and I'm trying to use the expanded editor view.

![Image of console with tons of errors](https://i.imgur.com/M73jiEP.png)

Issues show with default plugin settings.

**Comment by braamgenis** [comment]
@AlexGStapleton This no longer appears to be an issue. Please confirm when you get a chance.

**Comment by AlexGStapleton** [comment]
That's odd. I just tried it and it's still happening for me.

![](https://vgy.me/lNlEgI.png)

**Comment by braamgenis** [comment]
Could you give some specific steps to reproduce? I have only SO CSS and AGP active and when I navigate to Appearance > Custom CSS and open the expanded editor I don't see any JS errors.

**Comment by AlexGStapleton** [comment]
Oddly, that's all I did. Hm. Maybe the theme is related - what theme were you using? I was using Vantage at the time.

**Comment by braamgenis** [comment]
Nope. Also using Vantage.

**Comment by braamgenis** [comment]
Perhaps to do with WP version. I'm using development version `4.8-RC1-40849`

**Comment by AlexGStapleton** [comment]
I'm using the WordPress 4.8 release version.

**Comment by braamgenis** [comment]
Reinstalled 4.8 and still nothing. :confused: I'm going to put this one on ice for now. Will come back to it after some of the higher priority issues.

**Comment by Misplon** [comment]
@AlexGStapleton Is there anything I need to do to recreate besides having AGP Font Awesome Collection and PB activated? I'm not seeing any errors at the moment. I have the two activated.

**Comment by AlexGStapleton** [comment]
No. 😕 
I'm honestly not too sure why you guys can't replicate it but it's probably for the best if we put this on hold for the time being.

**Comment by Misplon** [comment]
Lots of open issues at the moment. Should we perhaps close until we can isolate the issue further?

**Comment by AlexGStapleton** [comment]
Sure.
