### ISSUE TITLE
Theme: Add a Light|Dark theme option

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-css#152]
Alex, do you perhaps want to add a box below CSS Revisions with a heading Theme. Within the box a full-width select field with Light default and then dark available.

**Comment by AlexGStapleton** [comment]
Can you please elaborate on what this would specifically change? Is it changing the CodeMirror theme, or the resulting website styling? If the CodeMirror theme, do you have a specific theme in mind or do you want to come up with a custom one? [Here's a list of the default CodeMirror themes](https://codemirror.net/demo/theme.html) - these aren't bundled, but we can add them.
