### ISSUE TITLE
Store CSS in external stylesheet to allow browsers to cache

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#17]
I've talked to a couple of developer friends and they've all stated that their biggest issue with this plugin is the fact the stylesheet isn't stored in an external stylesheet. While I'm personally fine with it being inline, I can understand why they would want this. I can imagine extensive changes made via the SiteOrigin CSS Editor could certainly add a lot of weight to each page load.

This also seems to be a popular thing to ask about, and suggest on the WordPress.org forum.

**Comment by gregpriday** [comment]
Yeah, this is definitely something we need.

**Comment by urShadoww** [comment]
Hi AlexGStapleton and gregpriday, I would like to know if the above-mentioned enhancement has been made part of the plugin or its still in the development phase?

**Comment by AlexGStapleton** [comment]
Unfourtantly, no activate development has started on this yet. It's still planned to be added in a future version. Sorry mate. :(

If you're up for it, consider making a pull request. 👍
