### ISSUE TITLE
[Feature Request] Add option to disable element selection in visual mode

### ISSUE THREAD

**Issue by boquiabierto** [siteorigin/so-css#2]
By disabling the dom-node-selection you enable native browser and js events so you can navigate to other locations (than the home page) and trigger events that f.e. display hidden or load ajax content.

**Comment by boquiabierto** [comment]
Oh, suddenly I found the “Navigate to” link, great (I’ve changed so many times the iframe src…)! So half way there. Great job guys!

**Comment by Misplon** [comment]
Super :) Glad to hear you've made progress. If anything else comes up, let us know.

Cheers
