### ISSUE TITLE
Allow copy, and pasting via context menu

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#20]
A user just asked me via premium support if they could copy and paste in the CSS editor. Turns out, they use the context menu (right click) and it doesn't include said functionality. This really needs to change due to this plugin being catered for less experienced users.

A quick Google suggests a 3rd party library will need to be used such as [clipboard.js](https://zenorocha.github.io/clipboard.js/) to allow for this as Codemirror doesn't seem to offer functionality for this out of the box.

**Comment by braamgenis** [comment]
Bit of a weird one. It all works as expected... as long as you right click exactly on the CodeMirror editor. The white space visible isn't actually all part of the editor, only the lines where you see line numbers are part of the editor.

E.g. not on the editor:
![context menu over non-editor white space](https://cloud.githubusercontent.com/assets/3822928/13743419/3c89fc5e-e9ea-11e5-91ce-26ae00a7d56f.png)

E.g. on the editor:
![context menu over editor white space](https://cloud.githubusercontent.com/assets/3822928/13743484/b232f42e-e9ea-11e5-8a60-117947922b16.png)

I'll still try find a way to make the editor options appear when right clicking anywhere, but this is a quick answer for users not wanting to use Ctrl+C, Ctrl+V etc.

**Comment by gregpriday** [comment]
Resolved by https://github.com/siteorigin/so-css/pull/21
