### ISSUE TITLE
Snippets search input, not searching

### ISSUE THREAD

**Issue by gomediapt** [siteorigin/so-css#23]
Thank you for your work Greg.

**Comment by AlexGStapleton** [comment]
It's slightly misleading, but basically, that icon isn't for a search - It's to open the inspector.

I, personally, think the icon should be changed. Maybe to dashicons-admin-tools or dashicons-editor-kitchensink. The latter makes the most sense imo.

**Comment by gregpriday** [comment]
This was inspired by the inspector in Google Chrome, but I see they've changed it to a slightly better icon. I'd be up for changing it to avoid confusion.

**Comment by gregpriday** [comment]
We're going to lower the priority for this quite a bit. We've since created a lot of documentation focused on using the magnifying glass icon. Changing the icon would involve rewriting and rerecording a lot of the documentation content and videos.
