### ISSUE TITLE
CSS comments are allowed (usefull), but css styles after comments are not read/applied 

### ISSUE THREAD

**Issue by gomediapt** [siteorigin/so-css#24]
CSS "// comments" are being alowed, witch is usefull, but invalidate subsequent css instructions.

**Comment by AlexGStapleton** [comment]
Hold up. // isn't the valid CSS comment syntax. It needs to be wrapped inside of /* */.

For example, 
`/* This is a comment **`

is a valid comment while

`// this is a comment`

isn't. For more information please refer to the [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/Comments).

**Comment by gregpriday** [comment]
One day we'll try support CSS preprocessors like SASS and LESS. These allow for the more standard comment syntax. For now, we'll be sticking to supporting standard CSS syntax.
