### ISSUE TITLE
The Menu Item ID should be displayed more prominently

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#25]
When a user clicks on a menu item it should favour the menu-item-NUMBER class. Currently it only really makes a passing reference by displaying it in the hierarchy bar and doesn't directly reference it in the selectors. This may lead to unnecessary questions about how to directly target menu items.

![](https://i.imgur.com/8SGD8cD.png)

**Comment by gregpriday** [comment]
Great idea. I'll think about how we can accomplish it, but ideally
SiteOrigin CSS should be more aware of all WordPress classes and elements.

For example, you should be able to drill into specific menus, posts,
comments widgets and obviously Page Builder elements.

There's probably a lot we can do with the interface to make dealing with
these common elements a lot easier.
