### ISSUE TITLE
Code is deleted after editing

### ISSUE THREAD

**Issue by nota-bene** [siteorigin/so-css#3]
SiteOrigin CSS is deleting part of my code when I use the visual editor.

That happens with this code:

```
/*--------------------------------------------------------------
## x >= 840px
--------------------------------------------------------------*/

@media screen and (min-width: 840px) {
	/* Primary Menu */
	.main-navigation .menu-item-has-children > a:after {
		color: #b51b1a;
	}
}
```

Let's say the SiteOrigin CSS editor has that piece of code and nothing else. I press the "eye" button, change something via the visual editor, and when I am back to the text editor, this is what I see:

```
/*--------------------------------------------------------------
## x >= 840px
--------------------------------------------------------------*/
@media screen and (min-width: 840px){
}

.entry-title a {
  color: #000000;
}
```

(In this example, the `.entry-title a` was the part I changed via the visual editor.)

I think it may have something to do with the comments. If I do the same test, but starting with this:

```
@media screen and (min-width: 840px) {
	/* Primary Menu */
	.main-navigation .menu-item-has-children > a:after {
		color: #b51b1a;
	}
}
```

The result is this:

```
@media screen and (min-width: 840px){
  /* Primary Menu */
.main-navigation .menu-item-has-children > a:after {
    color: #b51b1a;
  }

}

.entry-title a {
  color: #000000;
}
```

If I do the same test with this:

```
/*--------------------------------------------------------------
## x >= 840px
--------------------------------------------------------------*/

@media screen and (min-width: 840px) {
	.main-navigation .menu-item-has-children > a:after {
		color: #b51b1a;
	}
}
```

The result is this:

```
/*--------------------------------------------------------------
## x >= 840px
--------------------------------------------------------------*/
@media screen and (min-width: 840px){
}

.entry-title a {
  color: #000000;
}

```

Is this a bug or am I doing something wrong?

Thanks in advance.

**Comment by braamgenis** [comment]
Hi @nota-bene Apologies for the delayed response. This should have been fixed in the 1.0.4 release done on 10 November 2015. Please let us know if this is still a problem for you and we can reopen the issue to investigate further.
