### ISSUE TITLE
L10n: Add Support for GlotPress

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#30]
[Issue reported here](https://wordpress.org/support/topic/translate-130)

**Comment by gregpriday** [comment]
I assume just adding `Text Domain: so-css` to the plugin header will be enough?

**Comment by AlexGStapleton** [comment]
Yes. [Source](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#text-domains)
