### ISSUE TITLE
CSS Editor Action link is pointing to SiteOrigin Widgets Bundle

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#33]
The CSS Editor link on the plugins page is linking to the SiteOrigin Widgets Bundle widgets page rather than the custom CSS page.

To clarify, by action link, this is presumably what you're referring to.
![](https://i.imgur.com/xdTmuKG.png)

**Comment by gregpriday** [comment]
Oops. Careless copy pasting.
