### ISSUE TITLE
If more than one @import is present the Visual editor won't open

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#34]
If more than one @import is present the visual editor button will error on click and not open. For example, add the following two @import's to the editor.

```
@import url(https://fonts.googleapis.com/css?family=Roboto);
@import url(https://fonts.googleapis.com/css?family=Droid+Serif);
```

Then click the visual editor button. Nothing will appear and an error will be present in the browsers console which points to [this line](https://github.com/siteorigin/so-css/blame/develop/js/css.js#L162) as the cause of the error.

![](https://i.imgur.com/2qeNrff.png)

**Comment by gregpriday** [comment]
@braamgenis this seems to be coming from the CSS library we're using to parse the CSS. You've worked with this before. Do you want to take a shot at fixing this (and sending them another PR)?
