### ISSUE TITLE
IE 11: Copy and Paste no Longer works (and other issues)

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#35]
The copy and paste fix (context menu) ironically broke copy and paste in IE 11 in certain situations (making it either super complicated or impossible) and it also caused certain usability issues (like selecting text is a massive pain). 

Right click copy and paste doesn't work either - Paste is only visible when something is selected.

**Comment by gregpriday** [comment]
This is all controlled by Code Mirror, so it's possible that updating to the latest version will fix.

**Comment by AlexGStapleton** [comment]
I wasn't able to replicate this issue in the editor on codemirror.net, so you look to be right.
