### ISSUE TITLE
FireFox: Prevent selection of row number

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#42]
We should try and prevent the selection of row numbers that happens in FireFox. While I'm personally not able to replicate it, a user has reported that it also copied the row numbers for them. Regardless of this, row number selection doesn't seem to be intentional as it only seems to happen in FireFox.

![](https://i.imgur.com/61J8lZL.gif)

**Comment by gregpriday** [comment]
This seems like more of a Firefox bug. Those already have `user-select: none`. I tested this and the line numbers aren't copying for me either.
