### ISSUE TITLE
CSS Parsing: Comment suddenly forced onto a new line when Visual Editor openned

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#45]
On save, this:

```
/* BLOCKQUOTE FORMATTING*/
/* BLOCKQUOTE FORMATTING*/
/* BLOCKQUOTE FORMATTING*/
/* BLOCKQUOTE FORMATTING*/
/* BLOCKQUOTE FORMATTING*/
```

Becomes this:

```
/* BLOCKQUOTE FORMATTING*/

/* BLOCKQUOTE FORMATTING*/

/* BLOCKQUOTE FORMATTING*/

/* BLOCKQUOTE FORMATTING*/

/* BLOCKQUOTE FORMATTING*/
```

While not exactly a major issue, it's likely undesired for most situations.

![](https://i.imgur.com/0CvG9MR.gif)

Some other instances:
![](https://i.imgur.com/uGfCzSL.gif)
![](https://i.imgur.com/miLwG1V.gif)
![](https://i.imgur.com/SqHql6J.gif)

(sorry about the inspector - it's not rerecording them 😿 )

**Comment by AlexGStapleton** [comment]
@gregpriday Sorry! Forgot to include "suddenly". 🙍

**Comment by braamgenis** [comment]
Issue only in #43 
@AlexGStapleton This is something we'll probably just have to put up with for a little while. I don't think it will be trivial to change that only for comments and I think it's a fair trade to have a few newlines, for a CSS parser lib that works properly. :stuck_out_tongue:

**Comment by AlexGStapleton** [comment]
Oh no, this is 100% a minor issue at this stage. The important thing is that stuff like #38 isn't happening (which it's not), and everything else people can put up with. Well, for at least the time being anyway.

**Comment by AlexGStapleton** [comment]
I'm not too sure when, but this has somehow been fixed.

**Comment by Misplon** [comment]
Epic.
