### ISSUE TITLE
Add Settings link to installed plugin links

### ISSUE THREAD

**Issue by paaljoachim** [siteorigin/so-css#5]
Hey

It would be nice to add a settings link to the right of the Edit text link in the installed plugin screen.
(In general this would be good to have for all plugins.)

**Comment by gregpriday** [comment]
Hi there @paaljoachim - do you just mean a link to the actual editor interface? I like that idea.

**Comment by paaljoachim** [comment]
Hey Greg. Yeah just the standard links inside the Installed plugins screen below The plugin name.
For instance Akismet has:
Settings l Deactivate l Edit.

Just as a standard rule for any plugin. Have a default method. Adding Settings creates no question as to where the settings are located. Btw a very few plugins also add a link to support or other "vital" links. As it is the first place after having installed the plugin the user sees.
