### ISSUE TITLE
Request: Update MiniColors

### ISSUE THREAD

**Issue by markbranly** [siteorigin/so-css#50]
The current bundled version of MiniColors,  [2.1.7](https://github.com/claviska/jquery-minicolors/blob/2.1.7/jquery.minicolors.js), was released over 2 years. 

The [latest version](https://github.com/claviska/jquery-minicolors/blob/2.2.4/jquery.minicolors.js) includes support for color palettes. It would be fantastic to be able to make use of this feature in your plugin. 

(Also, awesome plugin!)

**Comment by gregpriday** [comment]
So true! I'll update this for the next release.
