### ISSUE TITLE
When GeoDirectory is enabled the inspector panel isn't present

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#51]
When the [GeoDirectory](https://wordpress.org/plugins/geodirectory/) (10k) plugin is enabled the inspector panel isn't present

Here's a copy of the console:

> Uncaught TypeError: Cannot read property 'timepicker' of undefined
>     at http://localhost/siteorigin/wp-content/plugins/geodirectory/geodirectory-assets/js/jquery.ui.timepicker.min.js?ver=4.6.1:1:34
>     at http://localhost/siteorigin/wp-content/plugins/geodirectory/geodirectory-assets/js/jquery.ui.timepicker.min.js?ver=4.6.1:2:16712
> inspector.min.js:1 Uncaught ReferenceError: Backbone is not defined
>     at http://localhost/siteorigin/wp-content/plugins/so-css/js/inspector.min.js?ver=1.1.2:1:354
>     at http://localhost/siteorigin/wp-content/plugins/so-css/js/inspector.min.js?ver=1.1.2:1:5819
> ?so_css_preview=1:5402 Uncaught TypeError: Cannot read property 'setDefaults' of undefined
>     at HTMLDocument.<anonymous> (http://localhost/siteorigin/?so_css_preview=1:5402:58)
>     at i (http://localhost/siteorigin/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:27449)
>     at Object.fireWith [as resolveWith] (http://localhost/siteorigin/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:28213)
>     at Function.ready (http://localhost/siteorigin/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:30006)
>     at HTMLDocument.K (http://localhost/siteorigin/wp-includes/js/jquery/jquery.js?ver=1.12.4:2:30368)

**Comment by braamgenis** [comment]
This issue seems to have resolved itself. :stuck_out_tongue: @AlexGStapleton Please confirm when you have a moment?

**Comment by AlexGStapleton** [comment]
Oh. That was easy. 😕
