### ISSUE TITLE
Move 3rd party lib changes to own source.

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/so-css#58]
We've made some changes to 3rd party lib source files here https://github.com/siteorigin/so-css/commit/47e7850a0985f009b6c504c36920b66f3cece7cc, which should rather be in our own source.

**Comment by AlexGStapleton** [comment]
Most of the modified libraries haven't been updated in a while so while this would be nice I don't think this is worth it until they need updating again. I'm going to close this for the time being.
