### ISSUE TITLE
Tricky issue of hover and non hover elements

### ISSUE THREAD

**Issue by paaljoachim** [siteorigin/so-css#6]
Clicking for instance the Site Title.
The default that shows up is the hover state (on my end atleast).
Changing this over to normal state seems a bit tricky. As when I begin to change the color it effects only the hover state.

This means there needs to be a clear differentiation of hover and normal state.

It is a well created plugin got to say that!

**Comment by gregpriday** [comment]
Thanks @paaljoachim :+1:

I'll keep this issue open and see what I can do next time I'm working on this plugin. I think I'm following what you're after.

**Comment by paaljoachim** [comment]
Great! Have a nice day Greg!

**Comment by braamgenis** [comment]
This issue seems to have been resolved.
