### ISSUE TITLE
Avoid vague element selectors

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#61]
A lot of the issues associated with usage is for people using generic element selectors like p, or span. We should avoid vague selectors in favor of more specific selectors and only allow elements to be present in selectors when it's justified.

**Comment by Misplon** [comment]
Thanks Alex. 

Do you have a specific example? 

Ideally, we'd need to move this this thread to whatever theme or plugin is the issue. It's a broad challenge so we'd need to address in a theme or widget level where possible.

**Comment by AlexGStapleton** [comment]
Hm. Maybe I wasn't specific enough. My suggestion is that we should try and avoid direct elements and such. Anything that's far too broad. For example, if you click a paragraph, we shouldn't suggest p as a potential selector as that'll effect _all_ paragraphs. I know it's obvious to us but people don't seem to understand that it'll affect as much as it does.

**Comment by Misplon** [comment]
Sweet, thanks for explaining. @gregpriday Would be best to take a look at this idea.

**Comment by gregpriday** [comment]
At the moment, we've really targeted users who understand CSS with this plugin. Removing certain selectors that our standard users would have wanted just so newer users don't misuse them doesn't suit the goal of SO CSS.
