### ISSUE TITLE
Easy Social Share Buttons 3: CodeMirror editor contents is slightly covered

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#62]
[Easy Social Share Buttons 3](https://codecanyon.net/item/easy-social-share-buttons-for-wordpress/6394476?ref=appscreo) has admin styling that will move CodeMirror editor under the line numbers on the left. 

![](https://i.imgur.com/HK2un9i.png)
![](https://i.imgur.com/T3M1N0f.png)

**Comment by Misplon** [comment]
@AlexGStapleton Do you have a copy of Easy Social Share Buttons 3?

**Comment by AlexGStapleton** [comment]
Unfortunately, I do not. 😞

**Comment by Misplon** [comment]
I've requested a copy from the author's on Twitter, unfortunately, no reply. If anyone would like to send us a copy of the plugin, we'd be happy to add a fix for this problem.

**Comment by gregpriday** [comment]
We can hope that https://github.com/siteorigin/so-css/issues/87 will fix the issue. If we're using what's in WordPress core, and another plugin still conflicts, then it's fair enough to require that plugin handles the fix.

**Comment by Misplon** [comment]
I'm happy to defer to #87.
