### ISSUE TITLE
Right-click paste anywhere in editor

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/so-css#63]
Currently you have to right-click on an editable line to be able to paste the clipboard contents. In a new editor there is only one editable which makes this awkward and unintuitive. We should see if we can allow right-clicks anywhere in the editor to paste clipboard contents.

**Comment by gregpriday** [comment]
Is this still happening? I remember testing it and it allowed you to paste
in other areas of the editor. Code Mirror should have a minimum height.
I'll double check when I get home.

**Comment by braamgenis** [comment]
Yeah, it's happening for me locally in develop. Haven't checked master though.

**Comment by AlexGStapleton** [comment]
I can confirm this is still happening in 1.1.5.
