### ISSUE TITLE
Check Gutenberg compat

### ISSUE THREAD

**Issue by braamgenis** [siteorigin/so-css#71]
Check the requirements for Gutenberg compat and makes sure we meet them.
See here: https://plugincompat.danielbachhuber.com

**Comment by Misplon** [comment]
@AlexGStapleton Do you think you can perhaps take a look for us and see how things look and report back?

**Comment by AlexGStapleton** [comment]
I've run some tests with the latest Gutenberg release and don't see any issues. 

With that said, there may be a tad disconnect during editing when certain changes aren't reflected when editing the page but that may be unavoidable without major issues.
