### ISSUE TITLE
Resolve PHP warnings

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-css#73]
The following warnings appear when `debug` is `true`. Tested with PHP `7.2.1`. It would be good to get these resolved if possible.

`Warning: krsort() expects parameter 1 to be array, boolean given in /Users/andrew/Dropbox/Sites/siteorigin/wp-content/plugins/so-css/so-css.php on line 483`

`Warning: array_keys() expects parameter 1 to be array, boolean given in /Users/andrew/Dropbox/Sites/siteorigin/wp-content/plugins/so-css/so-css.php on line 484`

**Comment by AlexGStapleton** [comment]
Resolved in #70.

During testing, this seems to happen very infrequently (I had to completely delete the data to test it). It's also easily resolved - simply create a revision.

**Comment by Misplon** [comment]
Hey man, thanks for the update. Why close though, the warnings are still
thrown. Ideally they shouldn’t be at all. Can give it prio 3.

**Comment by AlexGStapleton** [comment]
All good - I was getting worried for a second there. Let me know how you go mate. :)
