### ISSUE TITLE
Bug css for SO 2.6.6 admin.min.css

### ISSUE THREAD

**Issue by leehaira** [siteorigin/so-css#75]
I found a bug for a css in SO 2.6.6
.so-panels-dialog .so-visual-styles{
height: 100%;
See image: http://prntscr.com/jb5qgf
remove "height: 100%;" is done.

**Comment by AlexGStapleton** [comment]
Closing this in favor of the SiteOrigin Page Builder issue.

siteorigin/siteorigin-panels#530
