### ISSUE TITLE
Editor adds extra padding to Vantage header widgets

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#8]
I've found that when using the SO CSS editor in the expanded mode that the Vantage header widgets get pushed down to inside of the menu. This is an issue because the menu itself has a z-index higher than the widgets so they're hidden. This also doesn't reflect what is actually visible on the site.

Here's an image of the widgets moved down.

![Example of hidden widgets](https://i.imgur.com/PTJVkKP.png)

**Comment by AlexGStapleton** [comment]
Just for reference; the two widgets present in the image is a text side (on the right) and a SiteOrigin Social widget with only FaceBook active.

**Comment by braamgenis** [comment]
@AlexGStapleton I don't see this behaviour. Could you provide some more info? For example under Customize > Theme Settings > Layout > Masthead Layout, are you using Default Masthead or Logo In Menu? Any other header/menu layout custmizations?

**Comment by AlexGStapleton** [comment]
Oh I knew I had forgotten something - sorry! Unfortunately, I can't seem to replicate it anymore. :disappointed:

Well, this is awkward.

**Comment by braamgenis** [comment]
Haha, nice. :stuck_out_tongue:
