### ISSUE TITLE
Possible page not found issue when WordPress stored in different folder

### ISSUE THREAD

**Issue by Misplon** [siteorigin/so-css#9]
With WP in its own directory: https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory, the inspector is opening up to the theme's 404 page and not the home page.

**Comment by braamgenis** [comment]
I assume this is only happening when using [Method II](https://codex.wordpress.org/Giving_WordPress_Its_Own_Directory#Method_II_.28With_URL_change.29)
We were using the `site_url` [method](https://github.com/siteorigin/so-css/blob/develop/so-css.php#L189) to figure out where it should open initially, but this seems to be [wrong](https://wordpress.stackexchange.com/a/50605) :confused:  so I've changed it to use `home_url` instead.
