### ISSUE TITLE
PHP Warning: preg_replace() Compilation failed

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/so-css#97]
A premium user has reported the following error:

` Warning: preg_replace(): Compilation failed: escape sequence is invalid in character class at offset 4 in /web/htdocs/www.oliopoderepanolfo.it/home/wp-content/plugins/so-css/so-css.php on line 686`

This issue is linked [these two patterns ](https://github.com/siteorigin/so-css/blob/1.2.4/so-css.php#L682-L683)and appear to be tied to the usage of A.

Unlike #95, this code is actively used.

**Comment by psmits1567** [comment]
Hi I have the same problem currently
Compilation failed: escape sequence is invalid in character class at offset 4 in /www/wp-content/plugins/so-css/so-css.php on line 756

**Comment by psmits1567** [comment]
This happens with PHP 7.4 !!
After switching back to 7.2 the error is gone

**Comment by psmits1567** [comment]
The error starts as soon as you open the SiteOrigin visual CSS editor

**Comment by psmits1567** [comment]
It appears that after removing the css from the editor pane, and pasting it in again, the problem is gone!

**Comment by Misplon** [comment]
Hi, @psmits1567. Sorry to hear about the hassle. Thanks for keeping us updated. If the issue is resolved for the time being, that's good news. All the best with your website.

**Comment by Xamder19** [comment]
Hola, rengo el mismo problema, si pudieran echarme una mano por favor: Warning: preg_replace(): Compilation failed: escape sequence is invalid in character class at offset 4 in /home/customer/www/tuslikes.es/public_html/wp-content/plugins/so-css/so-css.php on line 756

Esta es la linea 756: $css = preg_replace( array_keys( $regex ), $regex, $css );

**Comment by Misplon** [comment]
Hi @Xamder19. We'll resolve this as soon as we can. For the time being, it would be best to disable debug in your WordPress wp-config.php file. Most likely, `WP_DEBUG` is currently set to `true`, try setting it to `false`.

https://wordpress.org/support/article/debugging-in-wordpress/#wp_debug

**Comment by Xamder19** [comment]
Thank you, I have already done it and continue the same. I will be attentive to your responses, thanks.

**Comment by Misplon** [comment]
Thanks. In your wp-config.php file you can perhaps try to insert above `WP_DEBUG` the following:

```
ini_set('display_errors','Off');
ini_set('error_reporting', E_ALL );
```
https://www.wpbeginner.com/wp-tutorials/how-to-turn-off-php-errors-in-wordpress/

**Comment by Xamder19** [comment]
For now the errors are no longer displayed, thanks

**Comment by Misplon** [comment]
Super, I'm glad that helped. In the future, if you need to troubleshoot an issue, you can enable debug. We'll look into this warning as soon as possible and release an update for SO CSS once it's resolved. Any updates to the issue will be posted here on GitHub in this issue. Thanks.
